name: Auto Tag When PR To Master

on:
  # push:
  #   branches:
  #     - master
  pull_request:
    branches:
      - master


jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set Git Config
        run: |
          git config --global user.email "weilun.huang@gogolook.com"
          git config --global user.name "wei-lun-huang"
      - name: Create Git Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event.action == 'closed' && github.event.pull_request.merged == true
        run: |
          pr_title="${{ github.event.pull_request.title }}"
          # if [[ -z "$pr_title" ]]; then
          #   echo "PR title is empty, skipping tag creation."
          #   exit 0
          # fi
          pr_body=$(echo "${{ github.event.pull_request.body }}" | grep -oP 'RC-\d+')
          # if [[ -z "$pr_body" ]]; then
          #   echo "PR body is empty, skipping tag creation."
          #   exit 0
          # fi
          git tag -a "$pr_title" -m "$pr_body"
          # git push origin "$pr_title"
          git push origin --tags
