name: Auto Tag When PR To Master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - develop
      - release
      - master
    types: [opened, synchronize]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set Git Config
        run: |
          git config --global user.email "weilun.huang@gogolook.com"
          git config --global user.name "wei-lun-huang"
      - name: Create Git Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'
        run: |
          pr_title="${{ github.event.pull_request.title }}"
          pr_body=$(echo "${{ github.event.pull_request.body }}" | grep -oP 'RC-\d+')
          git tag -a "$pr_title" -m "$pr_body"
          git push origin --tags
